### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by dptr** [telesoho/vscode-markdown-paste-image#6]
i downloaded a Visual Studio Code 1.14.1 and installed this extension, when i paste an image, it shows the path select text box, but when i press the enter key , no picture was pasted in the markdown file, neither any image was found in the file path.

**Comment by dptr** [comment]
i solved by add powershell.exe path to the environment variable PATH.

**Comment by Eucaly** [comment]
Could any one indicate the "exact content" for below?
* add powershell.exe path to the environment variable PATH?

**Comment by gusbemacbe** [comment]
Hello @Eucaly !

I have still the same problem. Here is the output:

```shell
PS C:\Users\gusbe> $env:path
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\gusbe\AppData\Local\Microsoft\WindowsApps;D:\gusbe\Applications\VSCode Insiders\bin
```

**Comment by gusbemacbe** [comment]
And I installed PowerShell 7, but it was not successful to copy and paste on VSCode:

```shell
PS C:\Users\gusbe>  $env:Path -split ';'
C:\Program Files\PowerShell\7
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\PowerShell\7\
C:\Users\gusbe\AppData\Local\Microsoft\WindowsApps
D:\gusbe\Applications\VSCode Insiders\bin
```

**Comment by ctlajoie** [comment]
As of powershell 6.0, the executable is named pwsh.exe

**Comment by jygzyc** [comment]
Extension not working no Vscode 1.51.0

**Comment by jmanthony3** [comment]
> Extension not working no Vscode 1.51.0

Extension for Windows 10 not working on VS Code v1.53.1

**Comment by alejandroarmas** [comment]
Extension not working on 1.55.2

**Comment by htqx** [comment]
1.57.1  
paste pic ok。
but paste regex string no working。
arch linux

**Comment by gusbemacbe** [comment]
> 1.57.1
> paste pic ok。
> but paste regex string no working。
> arch linux

On native Linux or on WSL? Did you install `xclip`?

**Comment by htqx** [comment]
> > 1.57.1
> > paste pic ok。
> > but paste regex string no working。
> > arch linux
> 
> On native Linux or on WSL? Did you install `xclip`?

yes. native arch linux.

According to xclip's information, there is more than one clipboard, but multiple:

primary

secondary

clipboard

buffer-cut

vscode editor using 1. markdown paste using 3.

So, not working

I think...

**Comment by Venom-Host** [comment]
I don't understand how to use this extension, it's recommended if you install "Foam" but anytime I take a snip-it of a image and then paste it into the md editor (vscode) it just says "Paste Image". I'm probably being a noob here, but sorry I don't get it :(

**Comment by gusbemacbe** [comment]
> For anyone else struggling to do this, I have written a simple `Python` script that I call from a VS Code shortcut to store the image (if in clipboard) to a folder in the root directory of the `.md` file and then store to clipboard the text to paste into the `.md` file that links to the image.
> ```python
> import os
> from PIL import ImageGrab
> import pyperclip
> import sys
> import tag_counter
> import timestamp as ts
> 
> class getClip:
> 	def __init__(self, mdPath, mdBaseName, imageDescription, imageTitle):
> 		img = ImageGrab.grabclipboard()
> 		if isinstance(img, type(None)):
> 			sys.exit("ERROR! Please copy an image.")
> 		else:
>                         filePath = mdPath
> 			relativeFilePath = "/".join([filePath, mdBaseName])
> 			try: os.mkdir(relativeFilePath)
> 			except OSError as error: print(error)
> 			when = ts.when()
> 			imageTitle = str.lower(imageTitle).replace(" ", "_")
> 			imageName = f"{imageTitle}_{when}.png"
> 			fileName = f"{relativeFilePath}/{imageName}"
> 			pasteName = f"./{mdBaseName}/{imageName}"
> 			img.save(fileName, format="PNG")
> 			fig_number = tag_counter.getCount(mdPath, mdBaseName)
> 			pyperclip.copy(\
> 				f"| ![]({pasteName}) |\n" + \
> 				"|:--:|\n" + \
> 				f"| {imageDescription} " + "\\\\(\\tag{" + f"{fig_number+1}" + "} \\label{fig:" + f"{imageTitle}" + "}\\\\) |"\
> 				)
> 			print(f"Completed {fileName}")
> if __name__ == "__main__":
> 	getClip(str(sys.argv[1]), str(sys.argv[2]), str(sys.argv[3]), str(sys.argv[4]))
> ```

@jmanthony3, does it work with us on company's computers when PowerShell is blocked?
